version: 0.2

phases:
  install:
    commands:
    - npm install n
    - n 18.0.0
    - pip install -r requirements.txt
    - npm install aws-cdk@2.24.1 --loglevel verbose
    - npm install --loglevel verbose
  build:
    commands:
    - npx cdk diff '*'
