version: 0.2

phases:
  install:
    commands:
    - npm install n
    - n 16.3.0
    - pip install -r requirements.txt
    - npm install aws-cdk@1.134.0 --loglevel verbose
    - npm install --loglevel verbose
    build:
      commands:
      - npm run cdk diff '*'
